### ISSUE TITLE
Error when indexing...

### ISSUE THREAD

**Issue by apaytuvi** [opencb/opencga#358] opened 2016-08-31 15:22 UTC
I never get my files indexed. I can see the following errors...

```
BulkWriteError{index=93, code=16837, message='The field 'studies.0.gt' must be an array but is of type Object in document {_id: "1_2506356_G_A"}', details={ }}, BulkWriteError{index=94, code=16837, message='The field 'studies.0.gt' must be an array but is of type Object in document {_id: "1_2506367_C_T"}', details={ }}, BulkWriteError{index=95, code=16837, message='The field 'studies.0.gt' must be an array but is of type Object in document {_id: "1_2506368_T_C"}', details={ }}, BulkWriteError{index=96, code=16837, message='The field 'studies.0.gt' must be an array but is of type Object in document {_id: "1_2991636_G_T"}', details={ }}, BulkWriteError{index=97, code=16837, message='The field 'studies.0.gt' must be an array but is of type Object in document {_id: "1_3023751_C_A"}', details={ }}, BulkWriteError{index=98, code=16837, message='The field 'studies.0.gt' must be an array but is of type Object in document {_id: "1_3260628_T_C"}', details={ }}, BulkWriteError{index=99, code=16837, message='The field 'studies.0.gt' must be an array but is of type Object in document {_id: "1_3260699_A_T"}', details={ }}]. 
	at com.mongodb.BulkWriteBatchCombiner.throwOnError(BulkWriteBatchCombiner.java:127)
	at com.mongodb.BulkWriteBatchCombiner.getResult(BulkWriteBatchCombiner.java:115)
	at com.mongodb.DBCollectionImpl.executeBulkWriteOperation(DBCollectionImpl.java:160)
	at com.mongodb.DBCollection.executeBulkWriteOperation(DBCollection.java:1737)
	at com.mongodb.DBCollection.executeBulkWriteOperation(DBCollection.java:1733)
	at com.mongodb.BulkWriteOperation.execute(BulkWriteOperation.java:93)
	at org.opencb.datastore.mongodb.MongoDBNativeQuery.update(MongoDBNativeQuery.java:171)
	at org.opencb.datastore.mongodb.MongoDBCollection.update(MongoDBCollection.java:341)
	at org.opencb.opencga.storage.mongodb.variant.VariantMongoDBAdaptor.insert(VariantMongoDBAdaptor.java:1401)
	at org.opencb.opencga.storage.mongodb.variant.VariantMongoDBWriter.write(VariantMongoDBWriter.java:123)
	at org.opencb.opencga.storage.mongodb.variant.MongoDBVariantStorageManager$1TaskWriter.apply(MongoDBVariantStorageManager.java:400)
	at org.opencb.commons.run.ParallelTaskRunner$TaskRunnable.run(ParallelTaskRunner.java:373)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Error processing batch 1
Abort task thread on fail

```

Any clue to solve this?

**Comment by pfurio** [comment] 2016-09-05 14:37
Hi,

Could you tell me which version you are using? We have been doing major changes to the indexation command line recently for the new release. Could you try it again with the new release-0.8.0 branch?  I just updated the documentation a bit (https://github.com/opencb/opencga/wiki/Indexing-Variant-Data-v0.8.0). Let us know if you need any help.

**Comment by apaytuvi** [comment] 2016-09-14 09:50
Hi @pfurio ,

I tried with the new release-0.8.0 branch and with the master branch. I never get my files indexed. See the atached figure...
![untitled](https://cloud.githubusercontent.com/assets/11228225/18507620/665328cc-7a71-11e6-9c42-4ea786d31956.png)

**Comment by pfurio** [comment] 2016-09-14 15:29
Hi @apaytuvi,

We just fixed a bug related with the indexation today that made the indexation not to finish (https://github.com/opencb/java-common-libs/commit/23991b1b7f2eac7435e81a1494006e1484981c85). The problem you are having with 0.8 could be caused by that. This should be solved if you pull the code again. 

I suppose that if you have the status INDEXING with version 0.8 is because you are already running the daemons as it is explained here https://github.com/opencb/opencga/wiki/Indexing-Variant-Data-v0.8.0#method-1-opencga-catalog-command-line. Can you confirm me that?

**Comment by apaytuvi** [comment] 2016-09-15 15:31
Now it works, thank you!

**Comment by j-coll** [comment] 2016-09-15 16:21
Perfect, closing the issue

**Closed by j-coll** 2016-09-15 16:21 UTC
